//material-tailwind and ui components
export {default as Modal} from '@material-tailwind/react/Modal'
export {default as ModalHeader} from '@material-tailwind/react/ModalHeader'
export {default as ModalBody} from '@material-tailwind/react/ModalBody'
export {default as ModalFooter} from '@material-tailwind/react/ModalFooter'
export {default as Button} from '@material-tailwind/react/Button'
export {default as Icon} from '@material-tailwind/react/Icon'
export {default as Input} from '@material-tailwind/react/Input'
export {default as GLogin} from '@mui/icons-material/Google'
export {default as GitLogin} from '@mui/icons-material/GitHub'
//components
export {default as MainHeader} from './header/MainHeader'
export {default as HomeFeed} from './body/HomeFeed'
export {default as DailyWord} from './body/DailyWord'
export {default as DayWord} from './body/WordOfTheDay'