//front-end
import Head from 'next/head'
import {
  MainHeader,
  TeamProfile,
  Icon,
  Button,
  Modal,
  ModalHeader,
  ModalBody,
  ModalFooter,
  AnimatedSlider
} from '../components/'
import { Doughnut } from 'react-chartjs-2'
import 'chart.js/auto'
import 'react-animated-slider/build/horizontal.css'
//back-end
import { bearPeeps, samples } from '../backend_services/'

export default function Home () {
  const data = {
    labels: ['Team', 'Giveaways', 'Pre-Sale', 'Public Mint'],
    datasets: [
      {
        label: 'Distribution of 10,000 Unique "The Bear Necessities" NFTs',
        data: [0.5, 0.5, 4, 95],
        borderColor: ['rgba(255,206,86,0.2)'],
        backgroundColor: [
          ' rgb(249, 115, 22)',
          'rgb(34,197,94)',
          'rgba(30,41,59)',
          'rgb(14,165,233)'
        ],
        pointBackgroundColor: 'rgb(126,34,206)'
      }
    ]
  }

  const options = {
    plugins: {
      title: {
        display: true,
        text: 'Distribution of 10,000 Unique "The Bear Necessities" NFTs',
        color: 'skyBlue',
        font: {
          size: 20
        },
        padding: {
          top: 20,
          bottom: 30
        },
        responsive: true,
        animation: {
          animateScale: true
        }
      }
    }
  }

  const data_second = {
    labels: ['Community', 'Charity', 'Team'],
    datasets: [
      {
        label: 'Distribution of Proceeds',
        data: [10, 15, 75],
        borderColor: ['rgba(255,206,86,0.2)'],
        backgroundColor: ['rgb(30,41,59)', 'rgb(14,165,233)', 'rgb(34,197,94)'],
        pointBackgroundColor: 'rgb(126,34,206)'
      }
    ]
  }

  const options_second = {
    plugins: {
      title: {
        display: true,
        text: 'Distribution of Proceeds',
        color: 'skyBlue',
        font: {
          size: 20
        },
        padding: {
          top: 20,
          bottom: 30
        },
        responsive: true,
        animation: {
          animateScale: true
        }
      }
    }
  }

  return (
    <div
      style={{
        backgroundImage:
          'url(https://enzosv.github.io/bearnecessitiesprojectnft/assets/cover.jpg)'
      }}
      className='
    h-screen
    overflow-hidden 
    bg-center
    bg-cover
    bg-no-repeat
    '
    >
      <Head>
        <title>BareBears</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <MainHeader />
      <main
        className='
      h-screen 
      bg-gray-700
      max-w-7xl 
      mx-auto
      opacity-95
      overflow-y-scroll
      scrollbar-hide
      pb-36
      font-font-smooch
      '
      >
        <div
          className='
        max-w-full 
        w-full 
        overflow-x-scroll
        scrollbar-hide
        h-[390px]
        bg-gray-900
        grid
        place-items-center
        '
        >
          <Button
            color='gray'
            buttonType='link'
            size='lg'
            rounded={false}
            iconOnly={false}
            block={false}
            ripple='dark'
            className='justify-self-center place-self-center'
          >
            <Icon name='lock' size='lg' />
          </Button>
        </div>
        <span
          className='
        grid 
        mx-auto 
        place-items-center 
        space-y-4 
        text-gray-50 
        font-font-smooch'
        >
          <h2 className=' font-light text-2xl'>Unlocks in</h2>
          <h1 className='font-normal text-4xl'>Q1 2022</h1>
        </span>
        {/**Background & vision */}
        <div
          className='
          grid 
          lg:grid-cols-2 
          grid-cols-1
          px-3
          items-center
          '
        >
          {/**left */}
          <div
            className='
          grid 
          space-y-3  
          px-5 
          py-4
          '
          >
            <h1
              className='
          lg:text-4xl 
          text-2xl 
          text-gray-50 
          font-light
          animate-pulse
          '
            >
              Background
            </h1>
            <p
              className='
            text-gray-50 
            text-base 
            font-font-smooch 
            font-extralight
            p-6
            max-w-3xl
            '
            >
              The Bear Necessities Project is a collection of 10,000 unique,
              collectible NFT bears living in the Ethereum blockchain. Each of
              these bears was heavily invested in the stock market and severely
              affected when everything came crashing down during the bear
              market. They all moved to the Ethereum blockchain and became NFTs
              in hopes that you will invest in them so they can all have a fresh
              start. Each bear is randomly generated from a set of individual
              traits, each conceptualized and hand-drawn over the course of a
              few months by our team’s artist, Peter Andrew Prado.
            </p>
            <h1
              className='
          lg:text-4xl 
          text-2xl 
          text-gray-50 
          font-light
          animate-pulse
          '
            >
              Vision
            </h1>
            <p
              className='
            text-gray-50 
            text-base 
            font-font-smooch 
            font-extralight
            p-6
            max-w-3xl
            '
            >
              Our vision is to be able to grow a wonderful and fun community
              behind The Bear Necessities Project while also being able to give
              back to other communities, including the communities that these
              bears were originally from. With that being said, we would also
              like to mention that we will be reserving 15% of all proceeds for
              donations to charity and other foundations, with 10% going
              specifically to WWF, and 5% toward various other organizations.
            </p>
          </div>
          {/**right */}

          <div
            className='
            grid 
            mx-auto
            place-items-center
           overflow-y-scroll
           scrollbar-hide
            h-[420px]
            w-[400px] 
            space-y-10
            bg-gray-600'
          >
            <AnimatedSlider
              autoplay={1000}
              touchDisabled
              infinite
              buttonDisabled
            >
              {samples.map(test => (
                <img
                  src={test.sample}
                  alt=''
                  className='
              h-[390px]
              w-[310px] 
              rounded-lg 
              shadow-lg 
              opacity-100 '
                />
              ))}
            </AnimatedSlider>
          </div>
        </div>
        {/**end of BG & Vision */}
        {/**Roadmap */}
        <div className='grid items-center space-y-3 px-3'>
          <h1
            className='
          lg:text-4xl 
          text-2xl 
          px-4
          py-5
          text-gray-50 
          font-light
          animate-pulse
          '
          >
            Roadmap
          </h1>
          <div className='grid lg:grid-cols-2 grid-cols-1 lg:space-y-0'>
            <div className=' font-font-smooch grid space-y-3 place-items-center p-4'>
              <h2 className='font-normal underline text-gray-50 text-2xl'>
                Community Airdop (3 NFTS)
              </h2>
              <h3 className='font-light text-gray-100 text-base'>
                NFT raffle for members using invite tracker (1 invite = 1
                ticket)
              </h3>
            </div>
            <div className=' font-font-smooch grid space-y-3 place-items-center p-4'>
              <h2 className='font-normal underline text-gray-50 text-2xl'>
                Pre-sale (300 NFTs)
              </h2>
              <h3 className='font-light text-gray-100 text-base'>
                Whitelisting for pre-sale (On Discord)
              </h3>
              <h3 className='font-light text-gray-100 text-base'>
                Actual pre-sale Surprise airdrop of 5 NFTs to 5 random pre-sale
                minters
              </h3>
            </div>
          </div>
          <div className='grid lg:grid-cols-2 grid-cols-1'>
            <div className=' font-font-smooch grid space-y-3 place-items-center p-4'>
              <h2 className='font-normal underline text-gray-50 text-2xl'>
                Milestone Airdrops (3 NFTs)
              </h2>
              <ul>
                <li>
                  <h3 className='font-light text-gray-100 text-base text-center'>
                    Airdrop for community members on Discord once Discord
                    community reaches a certain number of people (3k)
                  </h3>
                </li>
                <li>
                  <h3 className='font-light text-gray-100 text-base text-center'>
                    Airdrop for community members on Twitter once Twitter
                    followers reach a certain number of people (3k)
                  </h3>
                </li>
              </ul>
            </div>
            <div className=' font-font-smooch grid place-items-center p-4'>
              <h2 className='font-normal underline text-gray-50 text-2xl'>
                Minting
              </h2>
              <h3 className='font-light text-gray-100 text-base'>
                Unlocking of collection for minting on website
              </h3>
            </div>
          </div>
        </div>
        {/**End of RoadMap */}
        {/**Tokenomics */}
        <div
          className='
        grid
        px-3 
        mx-auto 
        max-w-full'
        >
          <h1
            className='
          lg:text-4xl 
          text-2xl 
          px-4
          py-5
          text-gray-50 
          font-light
          animate-pulse
          '
          >
            Tokenomics
          </h1>
          <div className='lg:grid-cols-2 grid-cols-1 grid items-center '>
            <div className='p-4'>
              <Doughnut data={data} options={options} />
            </div>
            <div className=' p-4'>
              <Doughnut data={data_second} options={options_second} />
            </div>
          </div>
        </div>
        {/**End of Tokenomics */}
        {/**Goals */}
        <div className='grid items-center space-y-3 px-3'>
          <h1
            className='
          lg:text-4xl 
          text-2xl 
          px-4
          py-5
          text-gray-50 
          font-light
          animate-pulse
          '
          >
            Goals
          </h1>
          <div className='grid lg:grid-cols-2 grid-cols-1 lg:space-y-0'>
            <div className=' font-font-smooch grid space-y-3 place-items-center p-4'>
              <h2 className='font-normal  text-gray-50 text-2xl underline'>
                25%
              </h2>
              <h3 className='font-light text-gray-100 text-base text-center'>
                5 The Bear Necessities NFTs released to 5 random NFT owners
              </h3>
            </div>
            <div className=' font-font-smooch grid space-y-3 place-items-center p-4'>
              <h2 className='font-normal text-gray-50 text-2xl underline'>
                50%
              </h2>
              <h3 className='font-light text-gray-100 text-center text-base'>
                10 more The Bear Necessities NFTs released to 5 random owners
              </h3>
            </div>
          </div>
          <div className='grid lg:grid-cols-2 grid-cols-1'>
            <div className=' font-font-smooch grid space-y-3 place-items-center p-4'>
              <h2 className='font-normal text-gray-50 text-2xl underline'>
                75%
              </h2>
              <h3 className='font-light text-gray-100 text-base text-center'>
                1 ETH to be airdropped to 5 random The Bear Necessities NFT
                owners
              </h3>
            </div>
            <div className=' font-font-smooch grid place-items-center p-4'>
              <h2 className='font-normal text-gray-50 text-2xl underline'>
                100%
              </h2>
              <h3 className='font-light text-gray-100 text-center text-base'>
                5 random The Bear Necessities owners get the chance to
                collaborate with our artist and create their own custom NFT 5
                ETH donated to charity
              </h3>
            </div>
          </div>
        </div>
        {/**End of Goals */}
        {/**Our Team */}
        <div
          className='
        grid 
        space-y-5 
        max-w-full 
        mx-auto 
        px-3'
        >
          <h1
            className='
          lg:text-4xl 
          text-2xl 
          px-4
          py-5
          text-gray-50 
          font-light
          animate-pulse
          '
          >
            Our Team
          </h1>
          <div className='lg:grid-cols-3 grid-cols-1 grid'>
            {/**TeamProfile.js */}
            {bearPeeps.slice(0, 3).map(data => (
              <TeamProfile
                pic={data.pic}
                name={data.name}
                nickname={data.nickname}
                job={data.job}
                job_2={data.job_2}
                job_3={data.job_3}
              />
            ))}
          </div>
          <div className='lg:grid-cols-3 grid-cols-1 grid'>
            {/**TeamProfile.js */}
            {bearPeeps.slice(3, 6).map(data => (
              <TeamProfile
                pic={data.pic}
                name={data.name}
                nickname={data.nickname}
                job={data.job}
                job_2={data.job_2}
                job_3={data.job_3}
              />
            ))}
          </div>
        </div>
        {/**End of Our Team */}
      </main>
    </div>
  )
}
