import Head from 'next/head'
import Sidebar from '../components/sidebar/Sidebar'
import Welcome from '../components/welcome/Welcome'

export default function Home () {
  return (
    <div className='bg-black flex overflow-hidden'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Sidebar />
      <Welcome />
    </div>
  )
}
